/**
 * Pakistan City List
 * Used in RFQ forms (city/delivery location) across web and mobile.
 * Ordered: major cities first, then alphabetical within tier.
 */
export const PAKISTAN_CITIES = [
  // Tier-1 (major metros)
  'Karachi',
  'Lahore',
  'Islamabad',
  'Rawalpindi',
  'Faisalabad',
  'Peshawar',
  'Quetta',
  'Multan',
  // Tier-2 (large cities)
  'Gujranwala',
  'Sialkot',
  'Bahawalpur',
  'Sargodha',
  'Sukkur',
  'Hyderabad',
  'Abbottabad',
  'Mardan',
  'Dera Ghazi Khan',
  'Gujrat',
  'Sheikhupura',
  'Rahimyar Khan',
  'Sahiwal',
  'Larkana',
  'Mirpur Khas',
  'Nawabshah',
  'Mingora',
  // Tier-3 (secondary cities)
  'Chiniot',
  'Kasur',
  'Dera Ismail Khan',
  'Kohat',
  'Nowshera',
  'Attock',
  'Chakwal',
  'Jhelum',
  'Muzaffarabad',
  'Mirpur (AJK)',
  'Turbat',
  'Gwadar',
  'Hub',
  'Khuzdar',
  'Khushab',
  'Vehari',
  'Okara',
  'Pakpattan',
  'Toba Tek Singh',
  'Jhang',
  'Khanewal',
  'Mianwali',
  'Hafizabad',
  'Narowal',
  'Kamoke',
  'Wazirabad',
] as const;

export type PakistanCity = (typeof PAKISTAN_CITIES)[number];

/** Format a city name with its Urdu romanisation hint (shown in bilingual UI) */
export const PAKISTAN_CITIES_URDU: Record<string, string> = {
  Karachi: 'کراچی',
  Lahore: 'لاہور',
  Islamabad: 'اسلام آباد',
  Rawalpindi: 'راولپنڈی',
  Faisalabad: 'فیصل آباد',
  Peshawar: 'پشاور',
  Quetta: 'کوئٹہ',
  Multan: 'ملتان',
  Gujranwala: 'گوجرانوالہ',
  Sialkot: 'سیالکوٹ',
  Bahawalpur: 'بہاولپور',
  Sargodha: 'سرگودھا',
  Sukkur: 'سکھر',
  Hyderabad: 'حیدرآباد',
  Abbottabad: 'ایبٹ آباد',
  Mardan: 'مردان',
  'Dera Ghazi Khan': 'ڈیرہ غازی خان',
  Gujrat: 'گجرات',
  Sheikhupura: 'شیخوپورہ',
  'Rahimyar Khan': 'رحیم یار خان',
  Sahiwal: 'ساہیوال',
  Larkana: 'لاڑکانہ',
  'Mirpur Khas': 'میرپور خاص',
  Nawabshah: 'نواب شاہ',
  Mingora: 'منگورہ',
};
